CC=gcc
CFLAGS = -W -pedantic -ansi -g
all: EMAILserver EMAILclient

EMAILserver: EMAILserver.c
	${CC} -w -o $@ ${CFLAGS} EMAILserver.c

EMAILclient: EMAILclient.c
	${CC} -w -o $@ ${CFLAGS} EMAILclient.c